name: Update the container calculator

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Étape pour configurer QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Étape pour configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape pour se déconnecter de Docker Hub (Nettoyage, au cas où)
      - name: Log out of Docker Hub (cleanup)
        run: docker logout

      # Étape pour se connecter à Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape pour vérifier le code source
      - name: Checkout the code
        uses: actions/checkout@v2

      # Étape pour construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./sources
          file: ./sources/Dockerfile
          push: true
          tags: aymengharbi/myrepo:1.0.${{ github.run_number }}
